### ISSUE TITLE
Dear, where can I get version 3.2.8 of Storage SCU Emulator?

### ISSUE THREAD

**Issue by jpgtama** [marcokemper/DVTk#1]
Our company is developing a medical software using this Emulator, and we have a tool validation of the version 3.2.8. So I need to find that version.

**Comment by marcokemper** [comment]
Hi,

the olderst version I was able to find (version from several years ago that was present on SourceForge) is Storage SCU Emulator 3.3.0.0.msi. Maybe you are able to find it on the internet or one your local drive?

Marco

**Comment by jpgtama** [comment]
Thank you for your reply. Not found on the internet or my local drive. Anyway, let me close this ticket.
